var dividendi = {
  uno:[1,"Arno Kütt","Valgetähe IV klass",,"Arno Kütt on pakiroboteid arendava Cleveroni juhatuse liige ja arendusjuht alates 2007. aastast. Viljandimaale loodud ettevõte oli mullu Äripäeva masina- ja metallitööstuse TOPis 15. kohal ning infotehnoloogia ja arvutifirmade pingereas 17. kohal.","https://www.aripaev.ee/embed/kumu_images/auhinnad2018/faces/Ipits.jpg","https://www.aripaev.ee/embed/kumu_images/auhinnad2018/auhinnad/valgetahe-4-klass.png"],
  dos:[2,"Heiti Hääl","Valgetähe III klass",,"Alexela Grupile 1990ndate keskel aluse pannud Heiti Hääl on praeguseks grupi juhatusest lahkunud ja alates 2014. aastast on kaasatud Alexela juhtimisse nõukogu tasemel. Alexela müügitulu oli 2017. aastal 228 562 924 eurot, kuid suurettevõte jäi tunamullu 4,3 miljoni euroga miinusesse. ",,"https://www.aripaev.ee/embed/kumu_images/auhinnad2018/auhinnad/valgetahe-3-klass.png"],
  tres:[3,"Oleg Gross","Valgetähe IV klass",,"Toidukaupade jaemüügiga tegeleva OG Elektra omanikku Oleg Grossi on varasemalt pärjatud Lääne-Virumaa edukaima ettevõtja tiitliga. Tema firmas töötab hetkel ligikaudu 1200 töötajat. 2017. aastal oli Gross Äripäeva rikaste TOPis 23. kohal ja tema vara suuruseks arvestati 88,2 miljonit eurot. ",,"https://www.aripaev.ee/embed/kumu_images/auhinnad2018/auhinnad/valgetahe-4-klass.png"],
  cuatro:[4,"Martin Villig","Valgetähe IV klass",,"Sõidujagamisteenust vahendava Taxify juhatuse liige Martin Villig tuli appi oma nooremale vennale Markus Villigule. Vendade käe all on Taxify’st saanud üks kiiremini kasvavaid ettevõtteid, mis näiteks 2017. aastal kasvatas käivet 507,79%. Martin Villig on seotud veel mitme iduettevõttega nagu näiteks Billify ja ühtlasi tegutseb ta ingel-investorina. ",,"https://www.aripaev.ee/embed/kumu_images/auhinnad2018/auhinnad/valgetahe-4-klass.png"],
  cinco:[5,"Tiit Pruuli","Valgetähe III klass",,"Reisiagentuuri GoTravel nõukogu esimees Tiit Pruuli on aktiivne ühiskonna tegelane, kes sai esmakordselt Eesti avalikkuse ees tuntuks president Lennart Meri pressiesindajana. 1998. aastal asus ta GoRaili nõukogu liikme kohale ning on jäänud grupiga seotud tänaseni. Lisaks Go Groupile on ta seotud mitmete MTÜ-dega ja lööb aktiivselt kaasa EV100 juhtrühma tegevuses.",,"https://www.aripaev.ee/embed/kumu_images/auhinnad2018/auhinnad/valgetahe-3-klass.png"],
  seis:[6,"Janek Vipre","Valgetähe V klass",,"Janek Vipre juhib Narma vaibavabrikut, mis on Lihulas vaipu tootnud üle 25 aasta. Kui president Kersti Kaljulaid vabrikut eelmisel aastal külastas, kiitis ta, et Narma on ehe näide sellest, et ka nišitootega võib olla globaalselt edukas ja tooteportfell ei pea olema väga lai, et olla oma valdkonnas tegija. Lihulast jõuavad vaibad mitmekümnesse riiki.",,"https://www.aripaev.ee/embed/kumu_images/auhinnad2018/auhinnad/valgetahe-5-klass.png"],
  siete:[7,"Tõnu Post","Valgetähe IV klass",,"Piimatootja Kõljala Põllumajanduslik OÜ juhataja Tõnu Post valiti eelmisel aastal silmapaistvamaks põllumajanduse tippjuhiks. Maaeluminister Tarmo Tamm meenutas siis, et Tõnu Post on Saaremaa suurima põllumajandusettevõtte juhina tunnustatud nii oma kodusaarel kui pälvinud muidki tiitleid – mõned aastad varem valiti ta ka Eesti aasta põllumeheks.",,"https://www.aripaev.ee/embed/kumu_images/auhinnad2018/auhinnad/valgetahe-4-klass.png"],
  ocho:[8,"Ülo Kivine","Valgetähe IV klass",,"2015. aastast Saaremaa Piimatööstust juhtinud Ülo Kivine on varem töötanud pikki aastaid Tere juures erinevatel ametikohtadel, viimati juhataja asetäitjana. Piimatööstuses on ta töötanud 1992. aastast, kui sattus tööle Tallinna piimakombinaati.",,"https://www.aripaev.ee/embed/kumu_images/auhinnad2018/auhinnad/valgetahe-4-klass.png"],
  nueve:[9,"Hans Kruusamägi","Valgetähe IV klass",,"Teravilja- ja kalakasvatuse Simuna Ivax juht on tuntud laiemalt kui Rukkikuningas, olles üks Eesti suurimaid rukkikasvatajaid. Ettevõte alustas 1993. aastal, viis aastat hiljem tehti algust ka kalakasvatusega. Veab Eesti Rukki Seltsiga algatust külvata Eesti 100. juubeliks 100 põllutäit rukkist ja valmistada sellest miljon juubelileiba.",,"https://www.aripaev.ee/embed/kumu_images/auhinnad2018/auhinnad/valgetahe-4-klass.png"],
  diez:[10,"Hans Kruusamägi","Valgetähe IV klass",,"Teravilja- ja kalakasvatuse Simuna Ivax juht on tuntud laiemalt kui Rukkikuningas, olles üks Eesti suurimaid rukkikasvatajaid. Ettevõte alustas 1993. aastal, viis aastat hiljem tehti algust ka kalakasvatusega. Veab Eesti Rukki Seltsiga algatust külvata Eesti 100. juubeliks 100 põllutäit rukkist ja valmistada sellest miljon juubelileiba.",,"https://www.aripaev.ee/embed/kumu_images/auhinnad2018/auhinnad/valgetahe-4-klass.png"],
  start: ['<div>President Kersti Kaljulaid annab Eesti Vabariigi 100. sünnipäeva eel riigi teenetemärgid tänuks 166 inimesele, kelle pühendumus oma kutsetööle või kogukonnale on muutnud kogu Eesti elu paremaks.</div><div>Vaata, kes on need ettevõtluses tegevad isikud, keda president tunnustab.</div>']
}