var texts = {
	pealkiri: 'Проверь себя: отгадай партию по предвыборному обещанию',
	selgitus: 'Парламентские выборы в Рийгикогу пройдут в Эстонии уже 3-го марта. ДВ рекомендует проверить, насколько хорошо вы знакомы с обещаниями партий. <br>Каждое обещаение имеет один правильный ответ. Максимально можно получить 32 очка.',
	footer_RU: '<span style="font-weight:700;align:right">Источник: </span>Äripäev &nbsp;/ <span style="font-weight:700">Графика:</span> Мигель Альварез  /<img src="https://static-page.aripaev.ee/embed/charts/2018/5/30/umbrikupalk/chartjs.hyperesources/logo.svg" style="float:right;width:72px;margin-top:-2px">'
}

var solution = {
	Q1: 'EKRE',
	Q2: 'Isamaa',
	Q3: 'Eesti200',
	Q4: 'Reformierakond',
	Q5: 'Vabaerakond',
	Q6: 'Rohelised',
	Q7: 'Keskerakond',
	Q8: 'Sotsid',
	Q9: 'Isamaa',
	Q10: 'Rohelised',
	Q11: 'Keskerakond',
	Q12: 'Reformierakond',
	Q13: 'EKRE',
	Q14: 'Reformierakond',
	Q15: 'Eesti200',
	Q16: 'Rohelised',
	Q17: 'Keskerakond',
	Q18: 'EKRE',	
	Q19: 'Isamaa',
	Q20: 'Vabaerakond',
	Q21: 'Vabaerakond',
	Q22: 'Sotsid',
	Q23: 'Eesti200',
	Q24: 'Sotsid',
};

var solution_RU = {
	Q1: 'EKRE',
	Q2: 'Isamaa',
	Q3: 'Eesti200',
	Q4: 'Реформисты',
	Q5: 'Свободная партия',
	Q6: 'Зеленые',
	Q7: 'Центристы',
	Q8: 'Соцдемы',
	Q9: 'Isamaa',
	Q10: 'Зеленые',
	Q11: 'Центристы',
	Q12: 'Реформисты',
	Q13: 'EKRE',
	Q14: 'Реформисты',
	Q15: 'Eesti200',
	Q16: 'Зеленые',
	Q17: 'Центристы',
	Q18: 'EKRE',	
	Q19: 'Isamaa',
	Q20: 'Свободная партия',
	Q21: 'Свободная партия',
	Q22: 'Соцдемы',
	Q23: 'Eesti200',
	Q24: 'Соцдемы',
};

var question = {
	Q1: 'Снизим налог с оборота до 15%',
	Q2: 'Сделаем накопительную пенсию добровольной',
	Q3: 'Выведем не менее 33% каждого государственного предприятия на биржу ',
	Q4: 'Президента должен выбирать парламент (Рийгикогу)',
	Q5: 'Упраздним II пенсионную ступень и позволим накопленные средства направлять в добровольную III пенсионную ступень, и при желании на определенных условиях изымать деньги',
	Q6: 'У банков, чья доля рынка превышает 25%, больше не будет возможности отказать в открытии расчетного счета предприятию, которое является резидентом Эстонии, без подробного письменного пояснения',
	Q7: 'Обеспечим молодым семьям возможность получения жилищного кредита под поручительство государства и без обязательного самофинансирования',
	Q8: 'Если государственный праздник выпадает на субботу или воскресенье, то понедельник сделаем выходным днем',
	Q9: 'Распределим выплату социального налога между работодателем и работником таким образом, чтобы зарплата не уменьшилась, а налоговое бремя не увеличивалось',
	Q10: 'Шаг за шагом уменьшим рабочую неделю c 40 часов до 32 часов в неделю',
	Q11: 'Поддерживаем введение простой и справедливой европейской системы прогрессивного подоходного налога',
	Q12: 'Установим не облагаемый налогом минимум 500 евро для всех налогоплательщиков',
	Q13: 'Установим условие для получения бесплатного высшего образования – после окончания университета человек должен будет проработать в Эстонии не менее 5 лет',
	Q14: 'За четыре года сократим число работающих в госсекторе людей минимум на 4000 человек',
	Q15: 'В течение следующих пяти лет в эстонскую экономику будет инвестировано не менее 50% общего объема пенсионных фондов',
	Q16: 'Сделаем безалкогольными заседания и голосования Рийгикогу',
	Q17: 'Поддержим религиозное обучение в качестве предмета по выбору',
	Q18: 'Установим вместе с предпринимателями 25 самых дорогостоящих и бюрократичных законов или постановлений, и аннулируем или переделаем их, чтобы сделать предпринимательскую среду более дружелюбной',	
	Q19: 'Увеличим расходы на оборону до 2,5% ВВП',
	Q20: 'Снизим подоходный налог с зарплаты с 20% до 12%',
	Q21: 'Ввести налог на нераспределенную прибыль юридических лиц, за исключением предприятий с малым оборотом',
	Q22: 'К 2024 году положим конец разведению животных для производства меха',
	Q23: 'Ставим своей целью, чтобы Таллиннская биржа объединилась с биржей Хельсинки',
	Q24: 'Поднимем границу ежемесячного дохода, начиная с которой снижается не облагаемый налогом минимум, с 1200 евро до 2000 евро',
};

var question_EE = {
	Q1: 'Alandame käibemaksu 15 protsendile',
	Q2: 'Muudame kogumispensioni kasutamise vabatahtlikuks',
	Q3: 'Viime vähemalt 33 protsenti igast riigiettevõttest börsile',
	Q4: 'Presidendi peaks eelistatult valima riigikogu',
	Q5: 'Kaotame ära praeguse II samba pensioni ja võimaldame inimestel sinna kogunenud raha suunata vabatahtliku kogumispensioni III sambasse ning soovi korral kokkulepitud tingimustel raha ka välja võtta ',
	Q6: 'Enam kui 25% turust omaval pangal kaob õigus keelduda arveldusarve avamisest Eesti residendi ettevõttele ilma sisulise kirjaliku põhjenduseta',
	Q7: 'Tagame noortele peredele võimaluse saada oma kodu soetamiseks eluasemelaenu riigi käendusel ning ilma kohustusliku omafinantseeringuta',
	Q8: 'Nädalavahetusele langeva riigipüha korral anname töötajale esmaspäeva vabaks',
	Q9: 'Jagame sotsiaalmaksu tasumise tööandja ja töötaja vahel nii, et palk ei vähene ja maksukoormus ei tõuse',
	Q10: 'Alandame sammhaaval tööajanormi 40 tunnilt 32 tunnile nädalas',
	Q11: 'Toetame õiglase ja lihtsa euroopaliku astmelise tulumaksusüsteemi kehtestamist',
	Q12: 'Kehtestame kõigile maksumaksjatele 500eurose igakuise tulumaksuvaba miinimumi',
	Q13: 'Seame tasuta kõrghariduse eelduseks, et lõpetanu töötab lõpetamise järel vähemalt viis aastat Eestis',
	Q14: 'Vähendame avalikus sektoris töötavate inimeste arvu nelja aastaga vähemalt 4000 inimese võrra',
	Q15: 'Järgneva viie aasta jooksul investeeritakse Eesti majandusse vähemalt 50 protsenti pensionifondide kogumahust',
	Q16: 'Teeme riigikogu istungid ja hääletused alkoholivabaks',
	Q17: 'Toetame usundiõpetuse laialdasemat pakkumist valikainena',
	Q18: 'Selgitame koostöös ettevõtjatega välja 25 kõige kulukamat ja bürokraatlikumat seadust või määrust ning tühistame need või teeme ümber, et muuta majanduskeskkonda ettevõtjasõbralikumaks',	
	Q19: 'Suurendame kaitsekulutusi 2,5%ni SKPst',
	Q20: 'Langetame tulumaksu palgatuludelt 20 protsendilt 12 protsendile',
	Q21: 'Maksustame juriidiliste isikute jaotamata kasumi. Maksustamist ei rakendata väikese käibega ettevõtete suhtes',
	Q22: 'Lõpetame Eestis 2024. aastast karusloomakasvatuse karusnaha tootmiseks',
	Q23: 'Seame eesmärgiks, et Tallinna börs ühineks Helsingi börsiga',
	Q24: 'Tõstame lisaastmete arvestamise tulumaksu piiri 1200 eurolt 2000 eurole kuus',
};