var winners = {
  uno:[1,"Veljo Ipits","Valgetähe IV klass","tõusnud","Veljo Ipits on töötanud Tartu Ülikooli majandusteaduskonnas vanemteaduri ja õppejõuna. Aastast 1988 on olnud eraettevõtjana tegev kaubanduses, mööblitööstuses, kinnisvaraäris. Peamine tegevusvaldkond on toiduainetööstus: ta on Salvesti omanik ning Eesti Toiduainetööstuse Liidu volikogu esimees.","https://www.aripaev.ee/embed/kumu_images/auhinnad2018/faces/Ipits.jpg","https://www.aripaev.ee/embed/kumu_images/auhinnad2018/auhinnad/valgetahe-4-klass.png"],
  dos:[2,"Heiki Einpaul","Valgetähe IV klass","kukkunud","Heiki Einpauli juhitav Hekotek projekteerib, valmistab ja käivitab puidutöötlemisettevõtetele tehnoloogilisi seadmeid. Ettevõte on juhtinud ka Äripäeva masina- ja metallitööstuse TOPi,  EAS valis Hekoteki 2016. aasta aasta ettevõtteks. Ettevõtte omanikeringi sai Einpaul selle esimese tegutsemisaasta lõpus – 1992. aastal.","https://www.aripaev.ee/embed/kumu_images/auhinnad2018/faces/Einpaul.jpg","https://www.aripaev.ee/embed/kumu_images/auhinnad2018/auhinnad/valgetahe-4-klass.png"],
  tres:[3,"Dmitri Demjanov","Valgetähe IV klass","kukkunud","Meie restoranikultuuri grand old maniks peetud Dimitri Demjanov on olnud aastast 1979 restorani Gloria direktori asetäitja ja direktor, aastast 1993 restoranide Gloria ja Egoist omanik. Ta on saanud muuhulgas Prantsuse gastronoomiaühenduselt Chaîne des Rôtisseurs aunimetuse Maître de Table Restaurateur ning Norra Kuningriigilt Rüütliristi. ","https://www.aripaev.ee/embed/kumu_images/auhinnad2018/faces/Demjanov.jpg","https://www.aripaev.ee/embed/kumu_images/auhinnad2018/auhinnad/valgetahe-4-klass.png"],
  cuatro:[4,"Olav Osolin","Valgetähe IV klass","tõusnud","Reklaamiguruks peetaval Olav Osolinil on telesaateid tootev ettevõte Kolm Karu.","https://www.aripaev.ee/embed/kumu_images/auhinnad2018/faces/Osolin.jpg","https://www.aripaev.ee/embed/kumu_images/auhinnad2018/auhinnad/valgetahe-4-klass.png"],
  cinco:[5,"Sirje Potisepp","Valgetähe V klass","kukkunud","Eesti toidu edendaja Sirje Potisepp on Eesti Toiduainetööstuse Liitu juhtinud alates 2005. aastast. Varem tegutses ta alkoholitootja Remedia juures, kus oli nii kommertsdirektor kui juhatuse ja nõukogu liige. Samuti on ta olnud Põhja-Tallinna linnaosavanem ja 2007. aastast Maaelu Edendamise Sihtasutuse nõukogus.","https://www.aripaev.ee/embed/kumu_images/auhinnad2018/faces/Potisepp.jpg","https://www.aripaev.ee/embed/kumu_images/auhinnad2018/auhinnad/valgetahe-5-klass.png"],
  seis:[6,"Janek Vipre","Valgetähe V klass","tõusnud","Janek Vipre juhib Narma vaibavabrikut, mis on Lihulas vaipu tootnud üle 25 aasta. Kui president Kersti Kaljulaid vabrikut eelmisel aastal külastas, kiitis ta, et Narma on ehe näide sellest, et ka nišitootega võib olla globaalselt edukas ja tooteportfell ei pea olema väga lai, et olla oma valdkonnas tegija. Lihulast jõuavad vaibad mitmekümnesse riiki.","https://www.aripaev.ee/embed/kumu_images/auhinnad2018/faces/Vipre.jpg","https://www.aripaev.ee/embed/kumu_images/auhinnad2018/auhinnad/valgetahe-5-klass.png"],
  siete:[7,"Tõnu Post","Valgetähe IV klass","kukkunud","Piimatootja Kõljala Põllumajanduslik OÜ juhataja Tõnu Post valiti eelmisel aastal silmapaistvamaks põllumajanduse tippjuhiks. Maaeluminister Tarmo Tamm meenutas siis, et Tõnu Post on Saaremaa suurima põllumajandusettevõtte juhina tunnustatud nii oma kodusaarel kui pälvinud muidki tiitleid – mõned aastad varem valiti ta ka Eesti aasta põllumeheks.","https://www.aripaev.ee/embed/kumu_images/auhinnad2018/faces/Post.jpg","https://www.aripaev.ee/embed/kumu_images/auhinnad2018/auhinnad/valgetahe-4-klass.png"],
  ocho:[8,"Ülo Kivine","Valgetähe IV klass","kukkunud","2015. aastast Saaremaa Piimatööstust juhtinud Ülo Kivine on varem töötanud pikki aastaid Tere juures erinevatel ametikohtadel, viimati juhataja asetäitjana. Piimatööstuses on ta töötanud 1992. aastast, kui sattus tööle Tallinna piimakombinaati.","https://www.aripaev.ee/embed/kumu_images/auhinnad2018/faces/Kivine.jpg","https://www.aripaev.ee/embed/kumu_images/auhinnad2018/auhinnad/valgetahe-4-klass.png"],
  nueve:[9,"Hans Kruusamägi","Valgetähe IV klass","kukkunud","Teravilja- ja kalakasvatuse Simuna Ivax juht on tuntud laiemalt kui Rukkikuningas, olles üks Eesti suurimaid rukkikasvatajaid. Ettevõte alustas 1993. aastal, viis aastat hiljem tehti algust ka kalakasvatusega. Veab Eesti Rukki Seltsiga algatust külvata Eesti 100. juubeliks 100 põllutäit rukkist ja valmistada sellest miljon juubelileiba.","https://www.aripaev.ee/embed/kumu_images/auhinnad2018/faces/Kruusamagi.jpg","https://www.aripaev.ee/embed/kumu_images/auhinnad2018/auhinnad/valgetahe-4-klass.png"],
  start: ['<div>President Kersti Kaljulaid annab Eesti Vabariigi 100. sünnipäeva eel riigi teenetemärgid tänuks 166 inimesele, kelle pühendumus oma kutsetööle või kogukonnale on muutnud kogu Eesti elu paremaks.</div><div>Vaata, kes on need ettevõtluses tegevad isikud, keda president tunnustab.</div>']
}