var winners = {
  uno:[1,"Arno Kütt","Valgetähe IV klass",,"Arno Kütt on pakiroboteid arendava Cleveroni juhatuse liige ja arendusjuht alates 2007. aastast. Viljandimaale loodud ettevõte oli mullu Äripäeva masina- ja metallitööstuse TOPis 15. kohal ning infotehnoloogia ja arvutifirmade pingereas 17. kohal.","https://s3.eu-central-1.amazonaws.com/aripaev-documents/embed/graph/2019/1/medals/img/arnukutt.jpg","https://s3.eu-central-1.amazonaws.com/aripaev-documents/embed/graph/2019/1/medals/img/valgetahe-4-klass.png"],
  dos:[2,"Heiti Hääl","Valgetähe III klass",,"Alexela Grupile 1990ndate keskel aluse pannud Heiti Hääl on praeguseks grupi juhatusest lahkunud ja alates 2014. aastast on kaasatud Alexela juhtimisse nõukogu tasemel. Alexela müügitulu oli 2017. aastal 228 562 924 eurot, kuid suurettevõte jäi tunamullu 4,3 miljoni euroga miinusesse. ","https://s3.eu-central-1.amazonaws.com/aripaev-documents/embed/graph/2019/1/medals/img/heitihaal.jpg","https://s3.eu-central-1.amazonaws.com/aripaev-documents/embed/graph/2019/1/medals/img/valgetahe-3-klass.png"],
  tres:[3,"Oleg Gross","Valgetähe IV klass",,"Toidukaupade jaemüügiga tegeleva OG Elektra omanikku Oleg Grossi on varem pärjatud Lääne-Virumaa edukaima ettevõtja tiitliga. Tema firmas töötab ligikaudu 1200 töötajat. 2017. aastal oli Gross Äripäeva rikaste TOPis 23. kohal ja tema vara suuruseks arvestati 88,2 miljonit eurot. ","https://s3.eu-central-1.amazonaws.com/aripaev-documents/embed/graph/2019/1/medals/img/oleggross.jpg","https://s3.eu-central-1.amazonaws.com/aripaev-documents/embed/graph/2019/1/medals/img/valgetahe-4-klass.png"],
  cuatro:[4,"Martin Villig","Valgetähe IV klass",,"Sõidujagamisteenust vahendava Taxify juhatuse liige Martin Villig tuli appi oma nooremale vennale Markus Villigule. Vendade käe all on Taxifyst saanud üks kiiremini kasvavaid ettevõtteid, mis näiteks 2017. aastal kasvatas käivet 507,79%. Martin Villig on seotud veel mitme iduettevõttega nagu näiteks Billify ja ühtlasi tegutseb ta ingel-investorina. ","https://s3.eu-central-1.amazonaws.com/aripaev-documents/embed/graph/2019/1/medals/img/martinvillig.jpg","https://s3.eu-central-1.amazonaws.com/aripaev-documents/embed/graph/2019/1/medals/img/valgetahe-4-klass.png"],
  cinco:[5,"Tiit Pruuli","Valgetähe III klass",,"Reisiagentuuri GoTravel nõukogu esimees Tiit Pruuli on aktiivne ühiskonna tegelane, kes sai esmakordselt Eesti avalikkuse ees tuntuks president Lennart Meri pressiesindajana. 1998. aastal asus ta GoRaili nõukogu liikme kohale ning on jäänud grupiga seotud tänaseni. Lisaks Go Groupile on ta seotud mitmete MTÜdega ja lööb aktiivselt kaasa EV100 juhtrühma tegevuses.","https://s3.eu-central-1.amazonaws.com/aripaev-documents/embed/graph/2019/1/medals/img/tiitpruuli.jpg","https://s3.eu-central-1.amazonaws.com/aripaev-documents/embed/graph/2019/1/medals/img/valgetahe-4-klass.png"],
  seis:[6,"Märten Vaikmaa","Valgetähe IV klass",,"Baltic Workboatsi suuromanik Märten Vaikmaa on seotud ka lennundusega – 2012. aastal kuulus ta mõnda aega Estonian Airi nõukokku, tunamullu aga liitus Tallinna Lennujaama nõukoguga ja on selle esimees. Vaikmaa on ka hobilendur. Ta on tegelenud ka kinnisvaraarendusega Kuressaare vanalinnas.","https://s3.eu-central-1.amazonaws.com/aripaev-documents/embed/graph/2019/1/medals/img/martenvaikmaa.jpg","https://s3.eu-central-1.amazonaws.com/aripaev-documents/embed/graph/2019/1/medals/img/valgetahe-4-klass.png"],
  siete:[7,"Jaak Nigul","Valgetähe IV klass",,"Mööblitööstuskontserni Tarmeko omanik Nigul on tuntud sotsiaalse närviga ettevõtjana. Nagu tänavu, nii ka juba 2012. aastal võttis ta sõna teenetemärkide jagamise loogika vastu leides, et neid võiksid saada ka tavalised töötajad. Detsembris lahkus ta aga Tartu linnavolikogust protestimaks selle vastu, et tema hinnangul läheb maamaksutõusust teenitav tulu linnavalitsuses palkade tõstmiseks. Samuti on ta kritiseerinud tuntud sotside tegevust maksude optimeerimisel, viidates silmakirjalikkusele. ","https://s3.eu-central-1.amazonaws.com/aripaev-documents/embed/graph/2019/1/medals/img/jaaknigul.jpg","https://s3.eu-central-1.amazonaws.com/aripaev-documents/embed/graph/2019/1/medals/img/valgetahe-4-klass.png"],
  ocho:[8,"Teet Kallakmaa","Valgetähe IV klass",,"OÜ Metstaguse Agro tegevjuht Kallakmaa on mitmekülgne põllumees – ta kasvatab teravilja, tunamullu pärjati teda maaeluminister Tarmo Tamme poolt aga ka parima piimakarjakasvataja tiitliga. Ta on ka piimandusühistu E-Piim nõukogu liige.","https://s3.eu-central-1.amazonaws.com/aripaev-documents/embed/graph/2019/1/medals/img/teetkallakmaa.jpg","https://s3.eu-central-1.amazonaws.com/aripaev-documents/embed/graph/2019/1/medals/img/valgetahe-4-klass.png"],
  nueve:[9,"Mark Aivo Takis","Valgetähe III klass",,"Takis on Eesti ja Baltimaade suurima ja vanima reisibüroo Estravel ASi asutaja. 2015. aastal ostis ta Finnairilt ka ettevõtte enamusosaluse välja. Lisaks on Takis tuntud Eesti asja ajajana Austraalias, mille eest teda ka president tänavu tunnustas. Ta on juhtinud Sydney Eesti Maja Kooperatiivi. ","https://s3.eu-central-1.amazonaws.com/aripaev-documents/embed/graph/2019/1/medals/img/markaivotakis.jpg","https://s3.eu-central-1.amazonaws.com/aripaev-documents/embed/graph/2019/1/medals/img/valgetahe-4-klass.png"],
  diez:[10,"Andres Lindam","Valgetähe IV klass",,"Lindamile kuulub pool Aru Grupist ning ta on ka ettevõtte tegevjuht. „Me oleme omavahel valdkonnad ära jaganud. Mina tegelen puidu poolega ja Andres Lindam põllumajandusega,“ kirjeldas äripartner Juhan Viise Äripäevale 2012. aastal meeste koostööd. Mullu töötas Aru Grupis 160 inimest, kasum aga enam kui kahekordistus 726 000 euroni. ","https://s3.eu-central-1.amazonaws.com/aripaev-documents/embed/graph/2019/1/medals/img/andreslindam.jpg","https://s3.eu-central-1.amazonaws.com/aripaev-documents/embed/graph/2019/1/medals/img/valgetahe-4-klass.png"],
  once:[11,"Margus Timmo","Valgetähe IV klass",,"President tunnustas Setomaa patriooti Timmot kohaliku elu edendamise eest. Timmo äride ampluaa on lai – ta on tegev turismi alal, aga kasvatab ka näiteks sõstraid. Härmä külas on mees taastanud ka esivanemate talu.","https://s3.eu-central-1.amazonaws.com/aripaev-documents/embed/graph/2019/1/medals/img/margustimmo.jpg","https://s3.eu-central-1.amazonaws.com/aripaev-documents/embed/graph/2019/1/medals/img/valgetahe-4-klass.png"],
  start: ['President Kersti Kaljulaid annab Eesti Vabariigi aastapäeva eel riigi teenetemärgid tänuks 112 inimesele, kelle pühendumus oma kutsetööle või kogukonnale on muutnud Eesti elu paremaks. Nende hulgas on ka palju tuntud ettevõtjaid']
}